import { Evento } from '../models/evento';

export const EVENTOS: Evento[] = [
  {
    id: 1,
    nome: "HackerSec Conference 2020",
    data: "sáb, 7 de março de 2020",
    local: "FIAP 1264 Avenida Lins de Vasconcelos Prédio 1 - Teatro Aclimação",
    hora: "08:00 – 18:00",
    valor: "R$90 – R$180",
    website: "https://www.eventbrite.com.br/e/hackersec-conference-2020-tickets-78440097443?aff=ebdssbdestsearch",
    organizacao: "Hacker Security",
    conteudo: "Promovido pela Hacker Security e aberto ao público o objetivo do evento HackerSec Conference é reunir os especialistas de cibersegurança mais conhecidos do Brasil para discutir sobre inovação na área de segurança da informação e mostrar na prática as armas cibernéticas.",
    imagem: "https://img.evbuc.com/https%3A%2F%2Fcdn.evbuc.com%2Fimages%2F78077459%2F302329341229%2F1%2Foriginal.20191024-153613?w=512&auto=format%2Ccompress&q=75&sharp=10&rect=0%2C120%2C1920%2C960&s=257b0d370ff695cb67a6aea2589eb9eb",
    
  },
  {
    id: 2,
    nome: "PHPeste 2020 Natal-RN",
    data: "2, 3, 4 Outubro de 2020",
    local: "Av. Lima e Silva, 76 - Lagoa Nova, Natal - RN, 59062-300",
    hora: "",
    valor: "",
    website: "https://phpeste.net/",
    organizacao: "PHPeste",
    conteudo: "	PHPeste 2020 será  na cidade de Natal/RN. Estamos organizando esse evento incrível para vocês, então entre no nosso grupo do Telegram e siga o @phpeste nas redes sócias para ficar por dentro das novidades.",
    imagem: "https://phpeste.net/assets/images/logo-prancheta-1.svg",
    
  },
  {
    id: 3,
    nome: "XIX Pylestras PUGCE",
    data: "30 de Abril de 2020",
    local: "UECE, Campus Itaperi: Av. Dr Silas Munguba, 1700 - Itaperi, Fortaleza CE",
    hora: "08:00 – 18:00",
    valor: "",
    website: "https://www.pylestras.org",
    organizacao: "PUGCE",
    conteudo: "O Pylestras é um evento sem fins lucrativo que consiste em um​ dia de palestras de tecnologia no qual palestrante e os convidados e/ou selecionados por votação compartilham sua experiência com estudantes e profissionais da área. Os assuntos das palestras são variados, contudo, orbitam o ecossistema da linguagem de programação​ Python.",
    imagem: "https://images.sympla.com.br/5db080cd16b7c.png",
    
  },
  {
    id: 4,
    nome: "GDI Online 2º Congresso online de Gestão de Documentos e Informações",
    data: "28 e 29 de Janeiro de 2020",
    local: "evento 100% na internet",
    hora: "",
    valor: "",
    website: "https://congresse.me/eventos/gdionline",
    organizacao: "https://congresse.me",
    conteudo: "2º Congresso online de Gestão de Documentos e Informações (GDIOnline2019) é um evento 100% na internet. Traz renomados profissionais da área de Ciência da Informação, Arquivologia, Biblioteconomia, Direito, Tecnologia da Informação, entre outros, que vão discutir uma temática complexa e com diversas vertentes.",
    imagem: "https://crb13.org.br/wp-content/uploads/2019/07/gdi-online-2019.png",
    
  },
  {
    id: 5,
    nome: "React.js Ceará 1º Meetup",
    data: "sáb, 18 de janeiro de 2020",
    local: "Agenda Edu, Rua Joaquim Nabuco, 2829 4º andar Dionísio Torres, CE 60125-121",
    hora: "",
    valor: "",
    website: "https://github.com/reactjs-ceara",
    organizacao: "React.js Ceará",
    conteudo: "Eai, vamos começar 2020 falando de React.js? Dia 18 de janeiro estaremos na Agenda Edu realizando nosso prímeiro meetup do ano.",
    imagem: "https://i0.hdslb.com/bfs/archive/d5cc9e285a3aeaaceee80598aaae378812935e17.jpg",
  },
  {
    id: 6,
    nome: "ARRETADAS DO PHP - LIVE night : BATE PAPO SOBRE EVENTOS ONLINE DAS COMUNIDADES ",
    data: "08 de Abril ",
    local: "Live Instagram",
    hora: "19:00 h",
    valor: "",
    website: "http://arretadas.phpcomrapadura.org/",
    organizacao: "Arretadas do PHP",
    conteudo: "Nosso grupo é formado por ARRETADAS do Ceará, que visam trazer mais mulheres para o mundo da tecnologia. Especialmente, PHP. Como extensão feminina do PHP com Rapadura, amamos o que fazemos. Porque aprender é bom, mas, compartilhar conhecimento é melhor ainda.",
    imagem: "http://arretadas.phpcomrapadura.org/img/profile.jpg",
  },
  {
    id: 7,
    nome: "Open Data Day Fortaleza",
    data: "11 de Abril de 2020",
    local: "Online Hangouts Meet",
    hora: "9:00 h as 19:00 h ",
    valor: "",
    website: "https://opendataday.org/pt_br/",
    organizacao: "Open Knowledge Brasil (OKBR)",
    conteudo: "O ODD Fortaleza 2020 discutirá Dados Abertos, Transparência e Pandemia. O evento será feito de maneira remota, utilizando o Hangouts Meet. O link para as inscrições está na bio. Na parte da manhã teremos palestras e à tarde oficinas.",
    imagem: "https://www.ok.org.br/wp-content/uploads/2020/04/odd-fortaleza-cropnw.jpg",
  },
  {
    id: 8,
    nome: "6° Encontro de devs PHP com Rapadura",
    data: "11 de Abril de 2020",
    local: "Online Redes Sociais ",
    hora: "14:00 h",
    valor: "Gratuito",
    website: "https://phpcomrapadura.org/",
    organizacao: "React.js Ceará",
    conteudo: "Venho aqui convidar-los a participar do nosso 'Encontro de devs PHP com Rapadura', esse ano por recomendações da Organização Mundial de Saúde o evento não pode ser realizado presencialmente, mas nós Cearenses arretados iremos disponibilizar uma LIVE ao vivo em todas as nossas redes sociais no dia 11 de Abril as 14:00hs. Contamos com a sua colaboração para arrecadar fundos que serão convertidos em cestas básicas e distribuídas nas comunidades carentes no estado do Ceará, um dos estados com maior números de casos confirmados do COVID-19 em todo Brasil.Então vocês podem ajudar colaborando com a nossa Vakinha e ajudando ao próximo além de assistir à um ótimo conteúdo de Tecnologia. http://bit.ly/vakinhacomrapadura",
    imagem: "https://i.ytimg.com/vi/-awTWE5f75I/maxresdefault.jpg",
  }
]

